# Generated by Django 5.2.15 on 2026-07-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tagline', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=50)),
                ('tags', models.JSONField(default=list)),
                ('image', models.ImageField(upload_to='products/')),
                ('rating', models.FloatField()),
                ('reviewcount', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
