# Generated by Django 5.2.15 on 2026-07-22 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=50)),
                ('ph_no', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[1-9]\\d{9,14}$')])),
                ('delivery_add', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=100)),
                ('order_notes', models.TextField()),
            ],
        ),
    ]
