# Generated by Django 5.2.15 on 2026-07-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_add',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='r_name',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ph_no',
            new_name='phone',
        ),
    ]
